### ISSUE TITLE
v0.2.x

### ISSUE THREAD

**Issue by thejmazz** [bionode/bionode-waterwheel#40]

**Comment by bmpvieira** [comment]
Current version is 0.4.0, can we close this?

**Comment by thejmazz** [comment]
Yes, maybe push these issues into a new milestone (or just leave them as standalone issues):

![image](https://cloud.githubusercontent.com/assets/1270998/24964588/aef8becc-1f6f-11e7-9ed1-5a5cf464423d.png)
