### ISSUE TITLE
Pipeline Graph (DAG) Visualization

### ISSUE THREAD

**Issue by thejmazz** [bionode/bionode-waterwheel#50]
It is useful to have a visual representation of the Directed Acyclic Graph (DAG) that is produced during the execution of a pipeline.

In the graph,
- each node is a task
- a node may use outputs from *n* parent nodes as input(s). each input value will be resolved from *one* node. this information is not currently stored. it could be done as an alternative edge type (or perhaps use discrete edge weightings for different edge types)
- *in these visualizations, think of three vertical `|` as the child node of two parent nodes. TODO actual graph diagrams*
- `join(A, B)` creates the DAG `a ---> b`
- `junction(A, B)` creates the DAG
```
a ---|
     |--->
b ---|
```
- `join(junction(A, B), C)` creates the DAG
```
a ---|
     |---> c
b ---|
```
- `join(A, fork(X, Y), C)` creates the DAG
```
      |---> x ---> c'
a --->|
      |---> y ---> c''
```

The redux reducer for the DAG is [here](https://github.com/bionode/bionode-watermill/blob/b19a8d38f6e7890697d350844dd1e8c1476b9256/lib/reducers/collection.js). It uses [graph.js](https://github.com/mhelvens/graph.js).

The graph exists in the store under the path `collection` (i.e. a valid selector would be `(state) => state.collection`.

A function [jsonifyGraph](https://github.com/bionode/bionode-watermill/blob/b19a8d38f6e7890697d350844dd1e8c1476b9256/lib/reducers/collection.js#L26-L52) is also exported. This is because the graph object from graph.js is not serializable. This creates a serializable JSON representation of the graph.

See [here](https://github.com/bionode/bionode-watermill/blob/cb22235fc6952997dee03c1478d906dc2e47e055/lib/lifecycle/resolve-input.js#L54) how the collection (aka DAG) is logged out during task resolution for debug.

A first implementation of this could be to write the JSON graph to disk during the pipeline execution, overwriting the previous file whenever a `ADD_OUTPUT` or `ADD_JUNCTION_VERTEX` actions have been dispatched (i.e. whenever the state of the DAG changes). This way if a task fails, at least we have the last best graph stored.

Then it is a matter of parsing that JSON into a visualization using something like [d3](https://d3js.org/).

Suggestions to improve the way the graph is handled within watermill are welcome. Perhaps there is a better serializable format to use (e.g. graphml format).

**BONUS**
- do it in a realtime with Electron/Browser app listening to changes in the redux store. new nodes should be added as the tasks run.

**Comment by thejmazz** [comment]
See the current JSON representation [here](https://github.com/bionode/bionode-watermill/blob/master/examples/pipelines/variant-calling-simple/log.txt). Note the duplicated logging of nodes if they are children of other nodes. This JSON graph structure is probably not ideal, or at least, should be created from another structure of `{ nodes: [], edges: []}`.

It could be useful to use a more standard graph format. The most ideal would be:

- serializable (so it can belong to redux state)
- can be loaded into a nice graph api

Some links:
- [GraphSON Format](https://github.com/thinkaurelius/faunus/wiki/GraphSON-Format)
- [GraphSON Reader and Writer Library](https://github.com/tinkerpop/blueprints/wiki/GraphSON-Reader-and-Writer-Library)
- [GraphSON file format parsing library using Node.js Streams](https://github.com/jbmusso/graphson)
- [SO: What is the most standard file format and notation for persisting expressive directed graphs?](https://stackoverflow.com/questions/16364294/what-is-the-most-standard-file-format-and-notation-for-persisting-expressive-dir)
- [a GML file](https://raw.githubusercontent.com/thejmazz/ontoscope-phylify/master/igraph/fantom.gml)

Even OBO could work: this could have nodes for a file, which might have an edge "created_by" and "used_by" to different task nodes

**Comment by tiagofilipe12** [comment]
We now have this kind of structure and a simple graph visualization with d3, available at localhost:8084 when watermill is running. Though, it still lacks `operationString`.

**Comment by tiagofilipe12** [comment]
Shall we close this? Of course graph visualization can be further improved but for now we have a simple DAG visualization tool.

**Comment by thejmazz** [comment]
Yes lets close for now. We can always make an issue for more specific improvements.
