### ISSUE TITLE
Check if file is empty

### ISSUE THREAD

**Issue by tiagofilipe12** [bionode/bionode-waterwheel#51]
While running a task watermill should check if file is empty before executing it. One simple way to do so would be to check if file size is 0.

**Comment by thejmazz** [comment]
There is [code](https://github.com/bionode/bionode-watermill/blob/7405aa272f285c13b97df2b1079a5ab80d27d466/lib/validators/is-non-null.js) for this but it was toggled off near the end of my GSOC. 

This is part of "validators", which can be ran before a task, after a task, and later we should add the ability for users to pass per filetype validators per task, stream validators (i.e. check if each object has required keys), etc

**Comment by thejmazz** [comment]
We should close this issue once that validation is re-enabled and we have tests for this

**Comment by tiagofilipe12** [comment]
Since I couldn't replicate this I will close it.
